### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by rpachaly** [ViRGIS-Team/mdal-python#10]
Hi all, 

I'm trying to use the MDAL-python library but I'm getting this error:

`ImportError: DLL load failed while importing libmdalpython: The specified module could not be found.`

Probably this is something easy to fix, but I still did not figure out. Can someone help me?

**Comment by runette** [comment]
Hi

First,  how are you loading mdal-python

If you are using pip, then as the README says you must have a working installation of MDAL on your machine. This is not brilliant and we are looking at ways of making this work better.

To get MDAL you can either use Conda ( my preferred way) or you build it yourself. The trick is that to user MDAL you need GDAL. If you use Conda then this is all taken care for you.

**Comment by rpachaly** [comment]
Hi Paul, 

It is working on my machine right now. I not totally sure, but it started working after I installed the QGIS DEVELOPERS TOOLS. 

I want to do some modifications on the MDAL and then test it using the mdal-python. Is it possible? 

Thanks!

**Comment by runette** [comment]
Entirely possible - I do that all the time. You need to build MDAL using your changes and then ensure that the MDAL binary that you have built is the one that is first in the search path.
